In [3]:
import pandas as pd

In [4]:
import numpy as np

In [11]:
x = np.array([12, 3, 6, 14])
print ("x: ", x)
print(type(x))
print("x.ndim: ", x.ndim)
print("x.shape: ", x.shape)
print(x[0])

x:  [12  3  6 14]
<class 'numpy.ndarray'>
x.ndim:  1
x.shape:  (4,)
12


In [13]:
x = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]
 ])
print(x[1,3])


8


In [14]:
print(type(x))
print("x.ndim: ", x.ndim)
print("x.shape: ", x.shape)
print(x[0])

<class 'numpy.ndarray'>
x.ndim:  2
x.shape:  (3, 4)
[1 2 3 4]


In [27]:
x = np.array([
 [[1, 2, 3, 4],     
  [5, 6, 7, 8],     
  [9, 10, 11, 12]],

 [[21, 22, 23, 24], 
  [25, 26, 27, 28], 
  [29, 30, 31, 32]]
 ])
print(x[0,1,2])


7


In [20]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[3:8])
print(arr[3:8:2])
print(arr[3:-1])
print(arr[3:])
print(arr[:5])

[3 4 5 6 7]
[3 5 7]
[3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10]
[0 1 2 3 4]


In [31]:
arr2 = arr.copy()
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [32]:
arr2 = arr
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [37]:
arr3 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
b = arr3.reshape(3, 4)
print(b)
b = arr3.reshape(2,2,3)
print(b)
b = arr3.reshape(2,2,-1)
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
