In [6]:
from sklearn.metrics import confusion_matrix
actual = [0, 1, 0, 1]
predicted = [1, 1, 1, 0]
cm = confusion_matrix(actual, predicted)
print(type(cm))

<class 'numpy.ndarray'>


In [7]:
print(" ", "0 ", "1 ", "P ")
print(0, "TN", "FP")
print(1, "FN", "TP")
print("A")
print()
print("confusion matrix")
print(cm)

  0  1  P 
0 TN FP
1 FN TP
A

confusion matrix
[[0 2]
 [1 1]]


In [9]:
r = cm.ravel()
print(type(r))
tn, fp, fn, tp = cm.ravel()
print("TN", tn, "FP", fp, "FN", fn, "TP", tp)

<class 'numpy.ndarray'>
TN 0 FP 2 FN 1 TP 1


In [11]:
#Confusion Matrix with Symbols
actual = ['B', 'M', 'B', 'M']
predicted = ['M', 'M', 'M', 'B']
# in aphabetical order, B is 0, M is 1
cm = confusion_matrix(actual, predicted)
print(" ", "B ", "M ", "P ")
print("B", "TN", "FP")
print("M", "FN", "TP")
print("A")
print()
print("CM", cm)

  B  M  P 
B TN FP
M FN TP
A

CM [[0 2]
 [1 1]]


In [12]:
#Confusion Matrix with Label
actual = ['W', 'M', 'W', 'M']
predicted = ['M', 'M', 'M', 'W']
# labels forces W to 0 (negative) and M to 1 (positive)
cm = confusion_matrix(actual, predicted, 
labels=["W", "M"])
print(" ", "W ", "M ", "P ")
print("W ", "TN", "FP")
print("M ", "FN", "TP")
print("A")
print()
print("CM", cm)


  W  M  P 
W  TN FP
M  FN TP
A

CM [[0 2]
 [1 1]]


In [13]:
#Non Binary Confusion Matrix
actual = ["cat", "ant", "cat", "cat", "ant", "bird"]
predicted = ["ant", "ant", "cat", "cat", "ant", "cat"]
cm = confusion_matrix(actual, predicted)
print(cm)
cm = confusion_matrix(actual, predicted, 
labels=["ant", "cat", "bird"])
print(cm)

[[2 0 0]
 [0 0 1]
 [1 0 2]]
[[2 0 0]
 [1 2 0]
 [0 1 0]]
