In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
df = pd.read_csv('data/iris.csv')
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [14]:
X = df.drop(['species'], axis='columns')
y = df.species
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=50, random_state=2, stratify= y)
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)
print('Accuracy', logmodel.score(X_test, y_test))
predictions = logmodel.predict(X_test)
# switch the labels around as 1 represents a negative, 
# 0 represents a positive
cm = confusion_matrix(y_test, predictions)
print(cm)

Accuracy 1.0
[[17  0  0]
 [ 0 17  0]
 [ 0  0 16]]
